# -*- coding: utf-8 -*-
"""Plant Care Chatbot.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-6q3lv9UKTZE2WzQtiLq3179ufNWJVx8
"""

# Install necessary libraries
!pip install sentence-transformers gradio

# Import Libraries
import pandas as pd
import re
from sentence_transformers import SentenceTransformer
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report
import numpy as np
import gradio as gr

# Upload data files
from google.colab import files

# Reading Plants Growth Data
plants_growth_df = pd.read_csv('/content/plants (1).csv', encoding='latin1')
print("Plants GrowthData has been read.✅")
plants_growth_df.head(2)

# Generate questions, answers, and intents
questions = []
answers = []
intents = []

for index, row in plants_growth_df.iterrows():
    plant = row['Plant Name']

    questions.append(f"What is the best soil for {plant}?")
    answers.append(f"The best soil for {plant} is {row['Soil']}.")
    intents.append("Soil")

    questions.append(f"How often should I water {plant}?")
    answers.append(f"Watering recommendation for {plant}: {row['Watering']}.")
    intents.append("Watering")

    questions.append(f"What sunlight is best for {plant}?")
    answers.append(f"{plant} prefers {row['Sunlight']}.")
    intents.append("Sunlight")

    questions.append(f"What type of fertilizer is recommended for {plant}?")
    answers.append(f"The recommended fertilizer for {plant} is {row['Fertilization Type']}.")
    intents.append("Fertilizer")

    questions.append(f"How fast does {plant} grow?")
    answers.append(f"{plant} has a {row['Growth']} growth rate.")
    intents.append("Growth")

plant_questions_df = pd.DataFrame({
    'question': questions,
    'answer': answers,
    'intent': intents
})

print(" Question and answer data has been created.✅")

# Text cleaning (Preprocessing)
def clean_text(text):
    text = text.lower()
    text = re.sub(r'[^a-zA-Z0-9\s]', '', text)
    text = re.sub(r'\s+', ' ', text).strip()
    return text

plant_questions_df['cleaned_question'] = plant_questions_df['question'].apply(clean_text)
print("✅ Texts cleaned")

# Download SBERT form
model = SentenceTransformer('all-MiniLM-L6-v2')

# Question Coding
questions_embeddings = model.encode(plant_questions_df['cleaned_question'].tolist(), show_progress_bar=True)
print(" The questions have been coded.✅")

#Building Retrieval Chatbot
def chatbot_response(user_question):
    user_question_clean = clean_text(user_question)
    user_embedding = model.encode([user_question_clean])
    similarities = cosine_similarity(user_embedding, questions_embeddings)[0]

    best_idx = np.argmax(similarities)
    best_question = plant_questions_df.iloc[best_idx]['question']
    best_answer = plant_questions_df.iloc[best_idx]['answer']
    best_intent = plant_questions_df.iloc[best_idx]['intent']
    best_score = similarities[best_idx]

    print(f"\n🔎 Closest Match: {best_question}")
    print(f"🔹 Intent: {best_intent}")
    print(f"🔹 Similarity Score: {round(best_score, 2)}")
    print(f"\n🪴 Answer: {best_answer}\n")
    print("🌱 Feel free to ask more questions about your plants!")


# Trying Chatbot
print("🌟 Chatbot is ready! You can now ask questions in the input below!")

# Intent Classification Model Training
print("✅ Now we start training Intent Classifier...")

# Preparing data for classification
X = plant_questions_df['cleaned_question']
y = plant_questions_df['intent']

# Split into training and testing
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Convert text to numbers using TF-IDF
vectorizer = TfidfVectorizer()
X_train_vec = vectorizer.fit_transform(X_train)
X_test_vec = vectorizer.transform(X_test)

# Building a classification model
intent_classifier = LogisticRegression(max_iter=1000)
intent_classifier.fit(X_train_vec, y_train)

# prediction
y_pred = intent_classifier.predict(X_test_vec)

# Model Evaluation
accuracy = accuracy_score(y_test, y_pred)

print(f"\n✅ Intent Classifier Accuracy: {round(accuracy*100, 2)}%")

print("\n📋 Classification Report:")
print(classification_report(y_test, y_pred))

# Fully prepared
print("\n🚀 Everything is ready! You have a complete Retrieval-based Chatbot and an Intent Classifier!")

# Chatbot: Continuous operation
while True:
    user_input = input("\n🌿 Ask me anything about plants (or type 'exit' to quit): ")
    if user_input.lower() == 'exit':
        print("👋 Goodbye! Take care of your plants!")
        break
    chatbot_response(user_input)

import gradio as gr

# --- define chatbot response function ---
def chatbot_response_gradio(user_question, history):
    user_question_clean = clean_text(user_question)
    user_embedding = model.encode([user_question_clean])
    similarities = cosine_similarity(user_embedding, questions_embeddings)[0]

    best_idx = np.argmax(similarities)
    best_question = plant_questions_df.iloc[best_idx]['question']
    best_answer = plant_questions_df.iloc[best_idx]['answer']
    best_intent = plant_questions_df.iloc[best_idx]['intent']
    best_score = similarities[best_idx]

    response = (
        f"🔎 Closest Match: {best_question}\n"
        f"🔹 Intent: {best_intent}\n"
        f"🔹 Similarity Score: {round(best_score, 2)}\n\n"
        f"🪴 Answer: {best_answer}\n\n"
        f"🌱 Feel free to ask more questions about your plants!"
    )

    history.append((user_question, response))
    return history

# --- build gradio app ---
with gr.Blocks(theme=gr.themes.Soft()) as demo:
    gr.Markdown("<h1 style='text-align: center; color: #4CAF50;'>🌿 Plant Care Chatbot</h1>")

    chatbot = gr.Chatbot(label="Plant Bot")
    user_input = gr.Textbox(placeholder="Ask about soil, watering, sunlight, etc...", show_label=False)

    with gr.Row():
        send_btn = gr.Button("Send", variant="primary")
        clear_btn = gr.Button("Clear Chat")

    send_btn.click(chatbot_response_gradio, [user_input, chatbot], [chatbot])
    user_input.submit(chatbot_response_gradio, [user_input, chatbot], [chatbot])
    clear_btn.click(lambda: [], None, chatbot)

demo.launch()